### ISSUE TITLE
Merging AOs?

### ISSUE THREAD

**Issue by andersaamodt** [AutonomousOrganization/ao-3#1]
Hi Taylor!

The React AO is looking really good and is about to get a big upgrade with isomorphic rendering. Maybe we can merge the React and Vue AOs again, or share more code between them? I'd be willing to look at converting it back to Vue 3, now that that's out.

Anders

**Comment by andersaamodt** [comment]
Nevermind! I am trying the new Vue 3 AO and it is slick, very streamlined! It's a very different experience from the React AO. The Vue 3 AO is optimized for a fast first-person navigation of cards, and fat has been cut, whereas with the React AO I focused on making interface elements a bit more standard and usable, and combining all previous features into one powerful main view. They are different views and both useful. I would like to have Vue 3 on my laptop, because it's more fun to navigate, and the React AO for community hubs.

So instead I suggest we standardize their API!

**Comment by AutonomousOrganization** [comment]
Was thinking the same thing

**Comment by AutonomousOrganization** [comment]
Shared server code separate frontend bundles makes sense too
