### ISSUE TITLE
right button doesn't clear priority

### ISSUE THREAD

**Issue by ZenenTreadwell** [AutonomousOrganization/ao-3#6]
After completing a prioritized task, I click on the dot to the right of in in expectation that the task will disappear and I will be rewarded with a small hit of dopamine. Instead, the task stays in place and I am left wondering where I went wrong in my life to deserve this fate

**Comment by AutonomousOrganization** [comment]
Added a little arrow that appears after a check that made moving to the completed area more obvious, but agree should put this back
